### ISSUE TITLE
Obsolete source line

### ISSUE THREAD

**Issue by nickandrew** [anl/puppet-chrome#1]
Hi,

In init.pp, the file source line uses deprecated syntax (will be removed in next puppet major release).

It should say:

"puppet:///modules/google-chrome/google.list"

**Comment by anl** [comment]
Thanks - it's been a while since I've used this module, I'll get it updated.

**Comment by anl** [comment]
This is fixed now - thanks for opening the issue.

In general, this entire module needs some love (even to get up to Puppet Style Guide standards); I may come back to it when I'm doing some more desktop deployments in the next couple months.

(Pull requests of course welcome!)

**Comment by nickandrew** [comment]
On Wed, Jul 18, 2012 at 06:01:21AM -0700, Andy Leonard wrote:

> This is fixed now - thanks for opening the issue.

Thanks for writing it :-)

I'm using puppet to control my laptop's configuration. So next time I do
an OS upgrade and it unexpectedly reformats my root filesystem, I'll be
able to get everything back just by running the puppet config.

> In general, this entire module needs some love (even to get up to Puppet Style Guide standards); I may come back to it when I'm doing some more desktop deployments in the next couple months.

I didn't notice any problem there :-)

Nick.
